
# Server configuration
server:
  port: 1314
  servlet:
    context-path:
  ssl:
    key-store: classpath:tjuyjn.top.jks
    key-store-password: vi80m2f3p5262
    key-store-type: JKS

# Spring configuration
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:  
    url : jdbc:mysql://localhost:3306/iron_man?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username : root
    password : root
    driverClassName : com.mysql.cj.jdbc.Driver
    
  jpa:   
    show-sql : true 
    open-in-view : true
   # hibernate:      
   #   ddl-auto: update      
   # naming:        
   #     physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy    
   #     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 
    
  
spring.thymeleaf.cache: false
server.tomcat.access_log_enabled: true  
server.tomcat.basedir: target/tomcat

 
# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  supercode: "99999"
  route:
    authentication:
      path: /api/login/
      register: /api/user/register/
#      refresh:

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
#spring.boot.admin.url: http://localhost:8080

# Tencent Cos
tencent:
  cos:
    secretId: "AKIDkP5lHXzqcKl5RYFSH9k5NVO4TZR2hWw6"
    secretKey: "3pNCk11kDPL4uU6RSGo58uQebeqlSu5D"
    region: "ap-beijing"
    bucket:  "iron-man-1303131952"
  wx:
    appid: "wx41443c3caff6ac73"
    secret: "a60e5a537d06c742310228e5f9cacc19"

#Mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.mbry.IronMan.entity